// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TP3_BD.Data;

#nullable disable

namespace TP3_BD.Migrations
{
    [DbContext(typeof(BiblioContext))]
    [Migration("20260119192713_NouvelleMigration")]
    partial class NouvelleMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TP3_BD.Entities.Activite", b =>
                {
                    b.Property<int>("ActiviteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActiviteId"));

                    b.Property<int>("CapaciteMax")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrganisateurId")
                        .HasColumnType("int");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ActiviteId");

                    b.HasIndex("OrganisateurId");

                    b.ToTable("Activites");
                });

            modelBuilder.Entity("TP3_BD.Entities.Auteur", b =>
                {
                    b.Property<int>("AuteurId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuteurId"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AuteurId");

                    b.ToTable("Auteurs");
                });

            modelBuilder.Entity("TP3_BD.Entities.Categorie", b =>
                {
                    b.Property<int>("CategorieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategorieId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategorieId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("TP3_BD.Entities.Employe", b =>
                {
                    b.Property<int>("EmployeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeId"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeId");

                    b.ToTable("Employes");
                });

            modelBuilder.Entity("TP3_BD.Entities.Emprunt", b =>
                {
                    b.Property<int>("EmpruntId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmpruntId"));

                    b.Property<DateTime>("DateEmprunt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateRetour")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateRetourPrevue")
                        .HasColumnType("datetime2");

                    b.Property<string>("Etat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LivreId")
                        .HasColumnType("int");

                    b.Property<int>("UsagerId")
                        .HasColumnType("int");

                    b.HasKey("EmpruntId");

                    b.HasIndex("LivreId");

                    b.HasIndex("UsagerId");

                    b.ToTable("Emprunts");
                });

            modelBuilder.Entity("TP3_BD.Entities.EmpruntMateriel", b =>
                {
                    b.Property<int>("EmpruntMaterielId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmpruntMaterielId"));

                    b.Property<DateTime>("DateEmprunt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateRetour")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateRetourPrevue")
                        .HasColumnType("datetime2");

                    b.Property<string>("Etat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaterielId")
                        .HasColumnType("int");

                    b.Property<int>("UsagerId")
                        .HasColumnType("int");

                    b.HasKey("EmpruntMaterielId");

                    b.HasIndex("MaterielId");

                    b.HasIndex("UsagerId");

                    b.ToTable("EmpruntsMateriel");
                });

            modelBuilder.Entity("TP3_BD.Entities.Evaluation", b =>
                {
                    b.Property<int>("EvaluationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EvaluationId"));

                    b.Property<string>("Commentaire")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateEvaluation")
                        .HasColumnType("datetime2");

                    b.Property<int>("LivreId")
                        .HasColumnType("int");

                    b.Property<int>("Note")
                        .HasColumnType("int");

                    b.Property<int>("UsagerId")
                        .HasColumnType("int");

                    b.HasKey("EvaluationId");

                    b.HasIndex("LivreId");

                    b.HasIndex("UsagerId");

                    b.ToTable("Evaluations");
                });

            modelBuilder.Entity("TP3_BD.Entities.Livre", b =>
                {
                    b.Property<int>("LivreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LivreId"));

                    b.Property<int>("Annee")
                        .HasColumnType("int");

                    b.Property<int>("AuteurId")
                        .HasColumnType("int");

                    b.Property<int>("CategorieId")
                        .HasColumnType("int");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Quantite")
                        .HasColumnType("int");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LivreId");

                    b.HasIndex("AuteurId");

                    b.HasIndex("CategorieId");

                    b.HasIndex("ISBN")
                        .IsUnique();

                    b.ToTable("Livres");
                });

            modelBuilder.Entity("TP3_BD.Entities.Materiel", b =>
                {
                    b.Property<int>("MaterielId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaterielId"));

                    b.Property<string>("Etat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantite")
                        .HasColumnType("int");

                    b.HasKey("MaterielId");

                    b.ToTable("Materiels");
                });

            modelBuilder.Entity("TP3_BD.Entities.Participation", b =>
                {
                    b.Property<int>("ParticipationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ParticipationId"));

                    b.Property<int>("ActiviteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateInscription")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Presence")
                        .HasColumnType("bit");

                    b.Property<int>("UsagerId")
                        .HasColumnType("int");

                    b.HasKey("ParticipationId");

                    b.HasIndex("UsagerId");

                    b.HasIndex("ActiviteId", "UsagerId")
                        .IsUnique();

                    b.ToTable("Participations");
                });

            modelBuilder.Entity("TP3_BD.Entities.Usager", b =>
                {
                    b.Property<int>("UsagerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsagerId"));

                    b.Property<bool>("Actif")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeUsager")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UsagerId");

                    b.ToTable("Usagers");
                });

            modelBuilder.Entity("TP3_BD.Entities.Activite", b =>
                {
                    b.HasOne("TP3_BD.Entities.Employe", "Organisateur")
                        .WithMany("ActivitesOrganisees")
                        .HasForeignKey("OrganisateurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Organisateur");
                });

            modelBuilder.Entity("TP3_BD.Entities.Emprunt", b =>
                {
                    b.HasOne("TP3_BD.Entities.Livre", "Livre")
                        .WithMany("Emprunts")
                        .HasForeignKey("LivreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TP3_BD.Entities.Usager", "Usager")
                        .WithMany("Emprunts")
                        .HasForeignKey("UsagerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Livre");

                    b.Navigation("Usager");
                });

            modelBuilder.Entity("TP3_BD.Entities.EmpruntMateriel", b =>
                {
                    b.HasOne("TP3_BD.Entities.Materiel", "Materiel")
                        .WithMany("Emprunts")
                        .HasForeignKey("MaterielId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TP3_BD.Entities.Usager", "Usager")
                        .WithMany("EmpruntsMateriel")
                        .HasForeignKey("UsagerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Materiel");

                    b.Navigation("Usager");
                });

            modelBuilder.Entity("TP3_BD.Entities.Evaluation", b =>
                {
                    b.HasOne("TP3_BD.Entities.Livre", "Livre")
                        .WithMany("Evaluations")
                        .HasForeignKey("LivreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TP3_BD.Entities.Usager", "Usager")
                        .WithMany("Evaluations")
                        .HasForeignKey("UsagerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Livre");

                    b.Navigation("Usager");
                });

            modelBuilder.Entity("TP3_BD.Entities.Livre", b =>
                {
                    b.HasOne("TP3_BD.Entities.Auteur", "Auteur")
                        .WithMany("Livres")
                        .HasForeignKey("AuteurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TP3_BD.Entities.Categorie", "Categorie")
                        .WithMany("Livres")
                        .HasForeignKey("CategorieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Auteur");

                    b.Navigation("Categorie");
                });

            modelBuilder.Entity("TP3_BD.Entities.Participation", b =>
                {
                    b.HasOne("TP3_BD.Entities.Activite", "Activite")
                        .WithMany("Participations")
                        .HasForeignKey("ActiviteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TP3_BD.Entities.Usager", "Usager")
                        .WithMany("Participations")
                        .HasForeignKey("UsagerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Activite");

                    b.Navigation("Usager");
                });

            modelBuilder.Entity("TP3_BD.Entities.Activite", b =>
                {
                    b.Navigation("Participations");
                });

            modelBuilder.Entity("TP3_BD.Entities.Auteur", b =>
                {
                    b.Navigation("Livres");
                });

            modelBuilder.Entity("TP3_BD.Entities.Categorie", b =>
                {
                    b.Navigation("Livres");
                });

            modelBuilder.Entity("TP3_BD.Entities.Employe", b =>
                {
                    b.Navigation("ActivitesOrganisees");
                });

            modelBuilder.Entity("TP3_BD.Entities.Livre", b =>
                {
                    b.Navigation("Emprunts");

                    b.Navigation("Evaluations");
                });

            modelBuilder.Entity("TP3_BD.Entities.Materiel", b =>
                {
                    b.Navigation("Emprunts");
                });

            modelBuilder.Entity("TP3_BD.Entities.Usager", b =>
                {
                    b.Navigation("Emprunts");

                    b.Navigation("EmpruntsMateriel");

                    b.Navigation("Evaluations");

                    b.Navigation("Participations");
                });
#pragma warning restore 612, 618
        }
    }
}
